module kernels_peridinamica
    use cudafor
    implicit none

    ! Define a precisão do tipo de dados
    integer, parameter :: dp = kind(1.0d0)

contains

    ! KERNEL 1: Conta quantos vizinhos cada nó tem no material
    attributes(global) subroutine count_neighbors_gpu(totnode, coord, delta, family_count)
        integer, value :: totnode
        real(dp), value :: delta
        real(dp), device :: coord(totnode, 2)
        integer, device :: family_count(totnode)

        integer :: i, j
        real(dp) :: dist, dx, dy

        ! Identifica qual thread é responsável por qual nó 'i'
        i = (blockIdx%x - 1) * blockDim%x + threadIdx%x

        if (i <= totnode) then
            family_count(i) = 0
            do j = 1, totnode
                if (i == j) cycle

                dx = coord(j,1) - coord(i,1)
                dy = coord(j,2) - coord(i,2)
                dist = sqrt(dx*dx + dy*dy)

                if (dist <= delta) then
                    family_count(i) = family_count(i) + 1
                end if
            end do
        end if
    end subroutine count_neighbors_gpu

    ! KERNEL 2: Preenche a lista nodefam
    attributes(global) subroutine fill_nodefam_gpu(totnode, coord, delta, family_pointer, family_nodes)
        integer, value :: totnode
        real(dp), value :: delta
        real(dp), device :: coord(totnode, 2)
        integer, device :: family_pointer(totnode)
        integer, device :: family_nodes(*) ! Ponteiro para o array unidimensional gigante

        integer :: i, j, k, start_idx
        real(dp) :: dist, dx, dy

        i = (blockIdx%x - 1) * blockDim%x + threadIdx%x

        if (i <= totnode) then
            k = 0 ! Contador local
            start_idx = family_pointer(i) ! Onde começa a lista deste nó

            do j = 1, totnode
                if (i == j) cycle

                dx = coord(j,1) - coord(i,1)
                dy = coord(j,2) - coord(i,2)
                dist = sqrt(dx*dx + dy*dy)

                if (dist <= delta) then
                    family_nodes(start_idx + k) = j
                    k = k + 1
                end if
            end do
        end if
    end subroutine fill_nodefam_gpu

    ! KERNEL 3: Responsável pelas boundary conditions
    attributes(global) subroutine apply_bc_gpu(total_internal, total_bottom, total_top, tt, dt, velocity, displacement)
        integer, value :: total_internal, total_bottom, total_top, tt
        real(dp), value :: dt
        real(dp), device :: velocity(total_top, 2), displacement(total_top, 2)

        integer :: i, idx

        ! Global thread ID
        i = (blockIdx%x - 1) * blockDim%x + threadIdx%x

        ! Mapeia a thread para o índice real do nó (começando após os nós internos)
        idx = total_internal + i

        if (idx <= total_top) then
            if (idx <= total_bottom) then
                ! Região da borda inferior (Bottom)
                velocity(idx, 2) = -20.0_dp
                displacement(idx, 2) = -20.0_dp * tt * dt
            else
                ! Região da borda superior (Top)
                velocity(idx, 2) = 20.0_dp
                displacement(idx, 2) = 20.0_dp * tt * dt
            end if
        end if
    end subroutine apply_bc_gpu


    ! KERNEL 4: Calcula Forças Peridinâmicas e Dano
    attributes(global) subroutine compute_force_damage_gpu(totnode, maxfam, coord, displacement, p_force, fail, damage, &
                                                           family_count, family_pointer, family_nodes, surface_correction, &
                                                           delta, radij, pi, bond_constant, vol, scr0, plate_length)
        implicit none
        integer, value :: totnode, maxfam
        real(dp), value :: delta, radij, pi, bond_constant, vol, scr0, plate_length
        real(dp), device :: coord(totnode, 2), displacement(totnode, 2)
        real(dp), device :: p_force(totnode, 2), surface_correction(totnode, 2)
        real(dp), device :: damage(totnode) ! Transformado em 1D
        integer, device :: family_count(totnode), family_pointer(totnode), family_nodes(*) ! Transformados em 1D
        integer, device :: fail(totnode, maxfam)

        integer :: i, j, cnode
        real(dp) :: dmg_par1, dmg_par2, idist, nlength, fac, theta, scx, scy, scr, dforce1, dforce2

        ! Identifica a thread global e mapeia para o nó 'i'
        i = (blockIdx%x - 1) * blockDim%x + threadIdx%x

        if (i <= totnode) then
            dmg_par1 = 0.0_dp
            dmg_par2 = 0.0_dp
            p_force(i,1) = 0.0_dp
            p_force(i,2) = 0.0_dp

            do j = 1, family_count(i)
                cnode = family_nodes(family_pointer(i) + j - 1)

                idist = sqrt((coord(cnode,1) - coord(i,1))**2 + (coord(cnode,2) - coord(i,2))**2)
                nlength = sqrt((coord(cnode,1) + displacement(cnode,1) - coord(i,1) - displacement(i,1))**2 + &
                               (coord(cnode,2) + displacement(cnode,2) - coord(i,2) - displacement(i,2))**2)

                ! Volume correction
                if (idist <= delta - radij) then
                    fac = 1.0_dp
                else if (idist <= delta + radij) then
                    fac = (delta + radij - idist) / (2.0_dp * radij)
                else
                    fac = 0.0_dp
                end if

                ! Determinação do angulo
                if (abs(coord(cnode,2) - coord(i,2)) <= 1.0d-10) then
                    theta = 0.0_dp
                else if (abs(coord(cnode,1) - coord(i,1)) <= 1.0d-10) then
                    theta = 90.0_dp * pi / 180.0_dp
                else
                    theta = atan(abs(coord(cnode,2) - coord(i,2)) / abs(coord(cnode,1) - coord(i,1)))
                end if

                ! Surface correction
                scx = (surface_correction(i,1) + surface_correction(cnode,1)) / 2.0_dp
                scy = (surface_correction(i,2) + surface_correction(cnode,2)) / 2.0_dp
                scr = 1.0_dp / (((cos(theta))**2 / (scx)**2) + ((sin(theta))**2 / (scy)**2))
                scr = sqrt(scr)

                if (fail(i,j) == 1) then
                    dforce1 = bond_constant * (nlength - idist) / idist * vol * scr * fac * &
                              (coord(cnode,1) + displacement(cnode,1) - coord(i,1) - displacement(i,1)) / nlength
                    dforce2 = bond_constant * (nlength - idist) / idist * vol * scr * fac * &
                              (coord(cnode,2) + displacement(cnode,2) - coord(i,2) - displacement(i,2)) / nlength
                else
                    dforce1 = 0.0_dp
                    dforce2 = 0.0_dp
                end if

                p_force(i,1) = p_force(i,1) + dforce1
                p_force(i,2) = p_force(i,2) + dforce2

                ! Definition of a no-fail zone
                if (abs((nlength - idist) / idist) > scr0) then
                    if (abs(coord(i,2)) <= (plate_length / 4.0_dp)) then
                        fail(i,j) = 0
                    end if
                end if

                dmg_par1 = dmg_par1 + fail(i,j) * vol * fac
                dmg_par2 = dmg_par2 + vol * fac
            end do

            ! Calculation of the damage parameter
            damage(i) = 1.0_dp - dmg_par1 / dmg_par2
        end if
    end subroutine compute_force_damage_gpu

    ! KERNEL 5: Integrador Temporal (Cinemática)
    attributes(global) subroutine integrate_kinematics_gpu(totnode, total_internal, dens, dt, p_force, b_force, velocity, displacement)
        implicit none
        integer, value :: totnode, total_internal
        real(dp), value :: dens, dt
        real(dp), device :: p_force(totnode, 2), b_force(totnode, 2)
        real(dp), device :: velocity(totnode, 2), displacement(totnode, 2)

        integer :: i
        real(dp) :: acc1, acc2

        ! Identifica a thread global e mapeia para o nó 'i'
        i = (blockIdx%x - 1) * blockDim%x + threadIdx%x

        if (i <= totnode) then
            ! Calcula aceleração (Força Peridinâmica + Força de Corpo)
            acc1 = (p_force(i,1) + b_force(i,1)) / dens
            acc2 = (p_force(i,2) + b_force(i,2)) / dens

            if (i <= total_internal) then
                ! Nós Internos: Integração livre em X e Y
                velocity(i,1)  = velocity(i,1) + acc1 * dt
                velocity(i,2)  = velocity(i,2) + acc2 * dt
                displacement(i,1) = displacement(i,1) + velocity(i,1) * dt
                displacement(i,2) = displacement(i,2) + velocity(i,2) * dt
            else
                ! Nós de Contorno (Boundary): Integrar apenas X.
                ! A velocidade/deslocamento em Y é forçada pelas BCs!
                velocity(i,1)  = velocity(i,1) + acc1 * dt
                displacement(i,1) = displacement(i,1) + velocity(i,1) * dt
            end if
        end if
    end subroutine integrate_kinematics_gpu

end module kernels_peridinamica
